[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "redis"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build:ws"]

[start]
cmd = "redis-server --daemonize yes && npm run ws:prod"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
healthcheckInterval = 10
healthcheckRetries = 3
healthcheckStartPeriod = 10

[deploy.env]
WS_PORT = "3001"
WS_HOST = "0.0.0.0"
NODE_ENV = "production"
NODE_OPTIONS = "--experimental-specifier-resolution=node"
REDIS_URL = "redis://localhost:6379" 