[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["npm run build:ws"]

[start]
cmd = "npm run ws:prod"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
healthcheckInterval = 10
healthcheckRetries = 3
healthcheckStartPeriod = 10

[deploy.env]
WS_PORT = "3001"
WS_HOST = "0.0.0.0"
NODE_ENV = "production" 