[build]
builder = "DOCKERFILE"
buildCommand = "npm run build:ws"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "redis-server --daemonize yes && sleep 5 && npm run ws:prod"
healthcheckPath = "/health"
sleepApplication = false
multiRegionConfig = { europe-west4-drams3a = { numReplicas = 1 } }
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 30
healthcheckInterval = 10
healthcheckStartPeriod = 120
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
NODE_OPTIONS = "--experimental-specifier-resolution=node"
REDIS_URL = "${REDIS_URL}"
WS_PORT = "3002"
WS_HOST = "0.0.0.0"
MONGODB_URI = "${MONGODB_URI}" 