[build]
builder = "DOCKERFILE"
buildCommand = "npm run build:ws"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "redis-server --daemonize yes && npm run start"
healthcheckPath = "/health"
sleepApplication = false
multiRegionConfig = { europe-west4-drams3a = { numReplicas = 1 } }
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 100
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
NODE_OPTIONS = "--experimental-specifier-resolution=node"
REDIS_URL = "redis://localhost:6379" 