[build]
builder = "DOCKERFILE"
buildCommand = "npm run build:ws"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "./scripts/startup.sh"
healthcheckPath = "/health"
sleepApplication = false
multiRegionConfig = { europe-west4-drams3a = { numReplicas = 1 } }
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 120
healthcheckInterval = 30
healthcheckStartPeriod = 300
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
NODE_OPTIONS = "--experimental-specifier-resolution=node"
REDIS_URL = "${REDIS_URL}"
WS_HOST = "0.0.0.0"
MONGODB_URI = "${MONGODB_URI}"

# Explicitly define exposed ports
[deploy.ports]
http.port = 8080
http.http2 = false
http.internal = false 